### ISSUE TITLE
Still Working?

### ISSUE THREAD

**Issue by gelinger777** [jcasoft/external-services#1]
Is this project functional for the Mycroft version of today?

**Comment by jjefferson13** [comment]
Not sure, I'm trying it and getting:

Traceback (most recent call last):
  File "/opt/mycroft/external-services/webchat.py", line 7, in <module>
    from mycroft.messagebus.service.ws import WebsocketEventHandler
ModuleNotFoundError: No module named 'mycroft.messagebus.service.ws'

**Comment by gelinger777** [comment]
@jjefferson13  seems dev dropped it.

**Comment by jcasoft** [comment]
I will try to update to the latest version of mycroft, on this date
